name:                webServer
version:             0.1.0.0
github:              "githubuser/webServer"
license:             BSD-3-Clause
author:              "gKrokod"
maintainer:          "@ofspb"
copyright:           "2024 gKrokod"

extra-source-files:
- README.md
- CHANGELOG.md
default-extensions:
- OverloadedStrings
- DeriveGeneric
- LambdaCase
- TypeApplications

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/webServer#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Werror
# - -Wcompat
# - -Widentities
# - -Wincomplete-record-updates
# - -Wincomplete-uni-patterns
# - -Wmissing-export-lists
# - -Wmissing-home-modules
# - -Wpartial-fields
# - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - text
    - bytestring
    - persistent-postgresql
    - aeson
    - persistent
    - time
    - monad-logger
    - template-haskell
    - esqueleto
    - wai
    - http-types
    - base64
    - binary
    - case-insensitive
    - cryptonite
    - mtl


executables:
  webServer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - webServer
    - warp
    - wai
    - text
    - time

tests:
  webServer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - webServer
    - hspec
    - QuickCheck
    - text
    - mtl
    - time
    - persistent-postgresql
    - http-types
    - wai
    - base64
    - binary
