name:                serverok
version:             0.1.0.0
github:              "githubuser/serverok"
license:             BSD3
author:              "gKrokod"
maintainer:          "@ofspb"
copyright:           "2024 gKrokod"

extra-source-files:
- README.md
- CHANGELOG.md

default-extensions:
- OverloadedStrings
- DeriveGeneric
- LambdaCase
# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/serverok#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
# - -Wall
- -Werror
# - -Wcompat
# - -Widentities
# - -Wincomplete-record-updates
# - -Wincomplete-uni-patterns
# - -Wmissing-export-lists
# - -Wmissing-home-modules
# - -Wpartial-fields
# - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - text
  - bytestring
  - aeson
  - wai
  - http-types
  - binary
  - base64
  - containers

executables:
  serverok-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - serverok
    - wai
    - warp
    # - http-types
    # - aeson

tests:
  serverok-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - serverok
